// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WestWindSystem.Entities
{
    public partial class Region
    {
        public Region()
        {
            Territories = new HashSet<Territory>();
        }

        [Key]
       
        public int RegionID { get; set; }
        [Required]
        [StringLength(50)]
        public string RegionDescription { get; set; }

        //this is a virtual mapping of the relationship
        //   between this file and another file
        //Territories on the database is related to Regions
        //this virtual property is indicating that any
        //  particular record in Regions is related
        //  to 0, 1 or more records in Territories

        
        public virtual ICollection<Territory> Territories { get; set; }
    }
}