// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WestWindSystem.Entities
{
    public partial class Territory
    {
        private string _TerritoryDescription;

        [Key]
 
        [StringLength(20)]
        public string TerritoryID { get; set; }
        [Required]
        [StringLength(50)]
        public string TerritoryDescription
        {
            get
            {
                return _TerritoryDescription.Trim();
            }
            set
            {
                _TerritoryDescription = value;
            }
        }

        public int RegionID { get; set; }

        //this is a virtual mapping of the relationship
        //   between this file and another file
        //Territories on the database is related to Regions
        //this virtual property is indicating that any
        //  particular record in Territories is related
        //  to a particular record in Region
        public virtual Region Region { get; set; }

       
    }
}